### ISSUE TITLE
Unable to install required meshzoo version (0.10.2)

### ISSUE THREAD

**Issue by trogke** [fraunhoferhhi/neural-deferred-shading#1]
Hello,

i tried to build the conda environment with the included environment.yml and ran into the following problem.
The required version of meshzoo (0.10.2) can not be found, instead conda suggests installing version 0.9.11.
A quick google search also did not turn up any information about meshzoo 0.10.2.

I have run the example (65_skull) and it seems that the project works with meshzoo 0.9.11.

**Comment by mworchel** [comment]
Hi,

thanks for the report.

there's been some weirdness with meshzoo lately and the author (accidentally?) removed this version from pypi (see https://github.com/meshpro/meshzoo/issues/93).

I've also tested the project with version 0.9.11 before and it seemed to work fine, just forgot to update the `environment.yml`.

I will remove the dependency on meshzoo soon. We're only using it for creating a sphere mesh and I think it's just not worth risking a broken environment again.
