### ISSUE TITLE
How did you create your camera position data? 

### ISSUE THREAD

**Issue by jaggzh** [fraunhoferhhi/neural-deferred-shading#10]
I'm guessing you rendered the imagery out, but would you happen to have a colmap conversion script? 
Oh, thanks a bunch. It's amazing work! :))

**Comment by mworchel** [comment]
Hi jagghz,

sorry for the long delay in answering. The DTU data is converted from the DTU subset in IDR format, [see the paragraph I have just added to the README](https://github.com/fraunhoferhhi/neural-deferred-shading?tab=readme-ov-file#data-conversion-from-idr-format-to-nds-format).

We do not have a COLMAP conversion script but it should be super straightforward to create one. Basically, our camera data is in standard OpenCV format (see [this section](https://github.com/fraunhoferhhi/neural-deferred-shading?tab=readme-ov-file#data-conversion-from-idr-format-to-nds-format) in the README). 

If you would like to be more specific about your use case, I might be able to assist in creating such a script.
