### ISSUE TITLE
Nerf data performance

### ISSUE THREAD

**Issue by JI0726** [fraunhoferhhi/neural-deferred-shading#5]
Has anyone tried this method in Lego or other scenes from nerf synthetic dataset? I find its reconstruction performance is limited.

**Comment by mworchel** [comment]
The topology of the objects in the NeRF dataset is pretty complex so I'd expect some challenges when using a mesh-based approach that doesn't handle topology changes. I'll close this issue for now. Feel free to create another issue if you have any other question.
