### ISSUE TITLE
Number of Multi View Images Required

### ISSUE THREAD

**Issue by AmanKishore** [fraunhoferhhi/neural-deferred-shading#7]
Hi,

This is great work!

How many multi-view images are required to generate an accurate mesh? 

Have you tried using Stable Diffusion to create those multi-views?

Thanks!

**Comment by mworchel** [comment]
Hi,

the number of required images depends a couple of factors and I guess there is no general rule. 360° coverage of the object would help because we strongly rely on mask supervision.

Regarding Stable Diffusion: we have so far verified our method only on real image data.

Best,
Markus
