### ISSUE TITLE
Issue Reproducing Evaluation Metric

### ISSUE THREAD

**Issue by tom-m-walker** [fraunhoferhhi/neural-deferred-shading#8]
Hi,

Thanks for sharing the code for this project! 
I'm trying to reproduce the Chamfer metric scores using the DTU evaluation script, however, the denormalized meshes produced are not aligned for comparison to the ground truth point clouds. Do you know where I can access the transformations necessary to realign them for evaluation?

Many thanks

**Comment by mworchel** [comment]
Hm, weird unless I'm missing something, the denormalized meshes should be aligned. Can the misalignment be classified? Just translation/rotation or wildly different alignments?

**Comment by tom-m-walker** [comment]
Thanks for the quick response. I've discovered the program I was using to convert obj --> ply was applying a rotation of 90 degrees for some reason!

**Comment by mworchel** [comment]
Great to hear! So I can consider this issue fixed? :)
